metadata.format.version = "1.1"

[versions]
minestom = "1_20_5-323c75f8a5"
logback = "1.4.5" # For tests only

nexuspublish = "1.3.0"

[libraries]
minestom = { group = "net.minestom", name = "minestom-snapshots", version.ref = "minestom" }

logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[bundles]
logback = ["logback-core", "logback-classic"]

[plugins]
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }
